### ISSUE TITLE
在mood列表上点击鼠标右键会报错然后闪退

### ISSUE THREAD

**Issue by botaofenghuo** [Hakoyu/StarsectorTools#12]
![屏幕截图 2023-05-11 225555](https://github.com/Hakoyu/StarsectorToolbox/assets/77828470/d26281da-510e-4586-b98f-def72c7c6671)

**Comment by Hakoyu** [comment]
啊 我之前对菜单项进行了修改忘记恢复
导致所有菜单都用不了
我的我的 (
