### ISSUE TITLE
首次启动选择游戏文件后闪退

### ISSUE THREAD

**Issue by jnxyp** [Hakoyu/StarsectorTools#5]
**复现方法**
1. 下载并安装控制台mod
2. 启动工具并选择游戏文件

**报错信息**
log文件内无有效输出，尝试直接运行源代码后提示：
![image](https://user-images.githubusercontent.com/16182688/209724175-1a32f59f-2736-434b-9d11-dacf69324806.png)
似乎是因为无法确定该mod的分类？

**Comment by Hakoyu** [comment]
已确认问题, 我之前修改过一次TypeGroup的判断方式, 没想到未知分组给挂掉了
添加一个`CheckTypeGroup`即可
![image](https://user-images.githubusercontent.com/48956359/210043044-a4986946-f876-4ace-a350-525dc3c700a2.png)
![image](https://user-images.githubusercontent.com/48956359/210043060-26439598-f773-4d8c-bcab-34dd209926fc.png)
会在下一个版本中修复
