### ISSUE TITLE
部分模组分类建议-文件来源中文论坛

### ISSUE THREAD

**Issue by BAKA24QWQ** [Hakoyu/StarsectorTools#8]
ID 名字 简介 分类
AMerchantsLegend 一个商人的传奇 依托于势力争霸的特殊开局 内容拓展
pantera_ANewLevel40R pantera_ANewLevel35R pantera_ANewLevel30R pantera_ANewLevel25R pantera_ANewLevel20R pantera_ANewLevel40 pantera_ANewLevel35 pantera_ANewLevel30 pantera_ANewLevel25 pantera_ANewLevel20 更高等级上限 功能模组
jc_asm 无人舰队拓展 & 幽灵部队 添加了一个全新的AI势力，以及与无人舰船配套的相关玩法 派系模组
fast_engine_rendering 快速引擎渲染 功能模组
star_federation 星际联邦 派系模组
HMI 风险矿业公司 派系模组
HMI_brighton 布莱顿联盟 派系模组
HMI_SV HMI反派势力 派系模组
leadingPip 预瞄框 功能模组
mik 蜜柑族群 派系模组
niko_morePlanetaryConditions 更多的行星环境 内容拓展
planet_search 星体搜索界面 功能模组
secretsofthefrontier 前线秘闻 有一条主线剧情 内容拓展
speedUp 战斗加速 功能模组
StopGapMeasures3 补漏措施 船包 内容拓展
stop_remove_dmod D插件修复禁用 闲杂模组
synDawnSkinPack 智械黎明美化包 修改了ai核心头像 美化模组
Templars 圣殿骑士团 甜不辣！ 派系模组
The_Lengend_Of_Tenshi 溶子的战役集 新增几个战役 内容拓展
ly_this_is_trash 这是破船 新增一个破船插件 闲杂模组
dynamictariffs 功能动态税率 功能模组

**Comment by Hakoyu** [comment]
好的 已收到
