### ISSUE TITLE
模组添加失败

### ISSUE THREAD

**Issue by BAKA24QWQ** [Hakoyu/StarsectorTools#9]
magiclib 前置
unknownskies 未知星域

**Comment by Hakoyu** [comment]
请描述如何添加失败 以及错误日志

**Comment by BAKA24QWQ** [comment]
将这两个模组置于mods文件夹内，启动BOX便跳出第一个弹窗，显示

模组添加失败 数量: 2
D:\远行星号\mods\MagicLib
D:\远行星号\mods\UnknownSkies

点击确定后，跳出第二个弹窗

已启用模组文件: D:\远行星号\mods\enabled_mods.json 未找到模组
MagicLib
US

没有单独跳出错误日志。
两个mod均在中文论坛下载最新版本，BOX无法读取但启动器中可以启动并正常进行游戏。

**Comment by Hakoyu** [comment]
这个是json错误了 下个版本会修复的
